name: Hello World

# Events

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:


# Workflow / Jobs

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello

        run: echo "Hello World"
        shell: bash